version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:220689@db:5432/mydb
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./documents:/app/documents  # связываем локальную папку с папкой в контейнере

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 220689
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:220689@db:5432/mydb
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./documents:/app/documents  # связываем локальную папку с папкой в контейнере, если нужно

volumes:
  postgres_data: