version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A tasks worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: