version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:220689@db:5432/mydb
      RABBITMQ_URL: amqp://rabbitmq:5672/
    volumes:
      - ./documents:/app/documents  # связываем локальную папку с папкой в контейнере

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 220689
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"         # Порт для AMQP
      - "15672:15672"       # Порт для управления RabbitMQ (Web UI)

  celery:
    build: .
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - rabbitmq
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:220689@db:5432/mydb
      RABBITMQ_URL: amqp://rabbitmq:5672/
    volumes:
      - ./documents:/app/documents  # связываем локальную папку с папкой в контейнере

volumes:
  postgres_data: